// Katalog aller vorgegebenen Übungen: Name, Muskeln, Stichwörter (umgangssprachliche und englische Namen für die Suche).
// Die ersten 32 Einträge sind die bisherigen Standardübungen (Namen NICHT ändern: Trainingspläne und Daten hängen daran).
// supabase/schema.sql enthält dieselben Übungen (erzeugt aus dieser Liste, ein Test prüft den Gleichstand).
import type { ExerciseType, MuscleId } from './types';

export interface CatalogExercise { name: string; type: ExerciseType; muscles: MuscleId[]; keywords: string }
type M = MuscleId;
const S = (name: string, muscles: M[], keywords = ''): CatalogExercise => ({ name, type: 'strength', muscles, keywords });
const C = (name: string, keywords = ''): CatalogExercise => ({ name, type: 'cardio', muscles: [], keywords });

export const CATALOG: CatalogExercise[] = [
  // ---- bisherige Standardübungen (Reihenfolge beibehalten) ----
  S('Bankdrücken', ['brust'], 'Bench Press, Flachbankdrücken, Langhantel Bankdrücken, Bank, Brustpresse mit Stange'),
  S('Schrägbankdrücken', ['brust'], 'Incline Bench Press, Schrägbank, obere Brust, Langhantel Schrägbank'),
  S('Kurzhantel-Bankdrücken', ['brust'], 'Dumbbell Bench Press, KH Bankdrücken, Kurzhanteln flach'),
  S('Butterfly', ['brust'], 'Pec Deck, Brustmaschine, Fly Maschine, Butterfly Maschine, Brust Fliegende Maschine'),
  S('Dips', ['trizeps', 'brust'], 'Barrenstütz, Dip Station, Dips am Barren, Parallelbarren'),
  S('Kniebeuge', ['quadrizeps', 'gesaess'], 'Squat, Back Squat, Kniebeugen, Langhantel Kniebeuge, Beugen'),
  S('Beinpresse', ['quadrizeps'], 'Leg Press, Beinpresse Maschine, Presse, 45 Grad Beinpresse'),
  S('Ausfallschritte', ['quadrizeps', 'gesaess'], 'Lunges, Ausfallschritt, Walking Lunges, Lunge'),
  S('Beinstrecker', ['quadrizeps'], 'Leg Extension, Beinstreckmaschine, Quadrizepsmaschine, Oberschenkel Maschine vorne'),
  S('Beinbeuger', ['beinbeuger'], 'Leg Curl, Beinbeugemaschine, liegend Beinbeuger, Oberschenkel Maschine hinten'),
  S('Wadenheben', ['waden'], 'Calf Raise, Wadenmaschine, Waden stehend, Wadenpresse'),
  S('Kreuzheben', ['unterer_ruecken', 'gesaess'], 'Deadlift, Konventionelles Kreuzheben, Heben, Totlift'),
  S('Rumänisches Kreuzheben', ['beinbeuger', 'gesaess'], 'RDL, Romanian Deadlift, Rumänisches, steifbeiniges Kreuzheben'),
  S('Klimmzüge', ['lat'], 'Pull Ups, Pullups, Klimmzug, Klimmzugstange, Obergriff Klimmzüge'),
  S('Latziehen', ['lat'], 'Lat Pulldown, Latzug, Latmaschine, Latzug zur Brust, Latissimus Ziehen'),
  S('Langhantelrudern', ['oberer_ruecken', 'lat'], 'Barbell Row, Rudern vorgebeugt, Bent Over Row, LH Rudern'),
  S('Kabelrudern', ['oberer_ruecken'], 'Seated Cable Row, Rudern am Kabel, enger Griff Rudern, Zugturm Rudern'),
  S('Schulterdrücken', ['schultern'], 'Overhead Press, OHP, Military Press, Schulterpresse, Langhantel Schulterdrücken'),
  S('Seitheben', ['schultern'], 'Lateral Raise, Seitenheben, Seitliches Heben Kurzhantel, seitliche Schulter'),
  S('Face Pulls', ['schultern'], 'Facepull, Face Pull, Kabelzug zum Gesicht, hintere Schulter Kabel, Rear Delt Kabel'),
  S('Bizepscurls', ['bizeps'], 'Biceps Curl, Curls, Langhantel Curl, SZ Curl, Bizeps Langhantel'),
  S('Hammercurls', ['bizeps'], 'Hammer Curl, Hammer Curls, Kurzhantel Hammer, neutraler Griff Curl'),
  S('Trizepsdrücken am Kabel', ['trizeps'], 'Pushdown, Trizeps Pushdown, Trizepsdrücken, Kabeldrücken Trizeps, Seil Trizeps'),
  S('French Press', ['trizeps'], 'Skull Crusher, Stirndrücken, Liegendes Trizepsstrecken, SZ Stange Trizeps'),
  S('Crunches', ['bauch'], 'Bauchpressen, Sit Ups, Bauchmuskeln Crunch, Bauchtraining'),
  S('Plank', ['bauch'], 'Unterarmstütz, Planke, Brett, Rumpfstabi, Core Stütz'),
  C('Laufband', 'Treadmill, Joggen Band, Running Band'),
  C('Crosstrainer', 'Ellipsentrainer, Elliptical, Cross Trainer'),
  C('Fahrradergometer', 'Ergometer, Standfahrrad, Spinning Bike, Radfahren Studio, Bike'),
  C('Rudergerät', 'Rower, Concept2, Ruderergometer, Rudern Cardio'),
  C('Stepper', 'Treppensteiger, Stairmaster, Stair Climber'),
  C('Laufen (draußen)', 'Joggen, Running, Outdoor Lauf, Laufrunde'),

  // ---- Brust ----
  S('Bankdrücken (Kurzhantel, Schrägbank)', ['brust'], 'Incline Dumbbell Press, KH Schrägbank, obere Brust Kurzhanteln'),
  S('Negativ-Schrägbankdrücken', ['brust'], 'Decline Bench Press, Negativbank, untere Brust, Decline Press'),
  S('Negativ-Bankdrücken (Kurzhantel)', ['brust'], 'Decline Dumbbell Press, Negativbank Kurzhantel, untere Brust'),
  S('Brustpresse (Maschine)', ['brust', 'trizeps'], 'Chest Press, Chest Press Maschine, Brustpresse, Pressmaschine Brust, sitzend Brust drücken'),
  S('Schrägbank-Brustpresse (Maschine)', ['brust', 'schultern'], 'Incline Chest Press Maschine, obere Brust Maschine, Schräge Brustpresse'),
  S('Bankdrücken (Smith-Maschine)', ['brust', 'trizeps'], 'Smith Machine Bench Press, Multipresse Bankdrücken, Smith Bankdrücken'),
  S('Schrägbankdrücken (Smith-Maschine)', ['brust', 'schultern'], 'Smith Machine Incline Press, Multipresse Schrägbank'),
  S('Fliegende (Kurzhantel)', ['brust'], 'Dumbbell Fly, Flys, Fliegende flach, Kurzhantel Fliegende, Butterfly Kurzhantel'),
  S('Fliegende (Schrägbank)', ['brust'], 'Incline Dumbbell Fly, Incline Fly, Fliegende schräg, obere Brust Fliegende'),
  S('Cable Crossover (Kabelzug)', ['brust'], 'Cable Fly, Kabelkreuzen, Crossover, Kabelzug Brust, Zugturm Brust, Kabel Flys'),
  S('Cable Crossover von unten', ['brust'], 'Low Cable Fly, obere Brust Kabel, Kabel von unten nach oben, Low to High Fly'),
  S('Cable Crossover von oben', ['brust'], 'High Cable Fly, untere Brust Kabel, Kabel von oben nach unten, High to Low Fly'),
  S('Liegestütze', ['brust', 'trizeps'], 'Push Ups, Pushups, Liegestütz, Klappmesser, Stütz Boden'),
  S('Liegestütze (Füße erhöht)', ['brust', 'schultern'], 'Decline Push Ups, Liegestütze Füße hoch, obere Brust Liegestütze'),
  S('Pullover (Kurzhantel)', ['brust', 'lat'], 'Dumbbell Pullover, Pullover, Überzüge, Pull Over'),
  S('Dips (Brust-Fokus)', ['brust', 'trizeps'], 'Brustdips, Chest Dips, Dips vorgebeugt, Dips Brust'),
  S('Dip-Maschine', ['trizeps', 'brust'], 'Assisted Dip, Dip Maschine, Dips an der Maschine, Dip Station Maschine'),
  S('Landmine Press', ['schultern', 'brust'], 'Landmine, Landminepress, Langhantel Ecke Drücken, einarmig Landmine'),

  // ---- Schultern ----
  S('Schulterdrücken (Kurzhantel)', ['schultern', 'trizeps'], 'Dumbbell Shoulder Press, KH Schulterdrücken, Schulterdrücken sitzend, Shoulder Press Kurzhantel'),
  S('Schulterdrücken (Maschine)', ['schultern', 'trizeps'], 'Shoulder Press Maschine, Schulterpresse, Schulterdrückmaschine, Maschine Schulter drücken sitzend'),
  S('Schulterdrücken (Smith-Maschine)', ['schultern', 'trizeps'], 'Smith Machine Shoulder Press, Multipresse Schulterdrücken, Smith Military Press'),
  S('Schulterdrücken (Langhantel, sitzend)', ['schultern', 'trizeps'], 'Seated Barbell Press, Langhantel sitzend, Schulterdrücken Bank'),
  S('Arnold Press', ['schultern'], 'Arnold Drücken, Arnold Schulterdrücken, Kurzhantel Drehdrücken, Arnolds'),
  S('Push Press', ['schultern', 'trizeps'], 'Stoßdrücken, Impulsdrücken, Schulterdrücken mit Beinschwung'),
  S('Seitheben (Maschine)', ['schultern'], 'Lateral Raise Maschine, Seitheben Maschine, Seitliche Schulter Maschine, Schulter Seitenheber'),
  S('Seitheben (Kabel)', ['schultern'], 'Cable Lateral Raise, Kabel Seitheben, einarmig Seitheben Kabel, Zugturm Seitheben'),
  S('Seitheben (Kurzhantel, vorgebeugt)', ['schultern', 'oberer_ruecken'], 'Rear Delt Raise, hintere Schulter, Reverse Fly Kurzhantel, Vorgebeugtes Seitheben, Reverse Flys'),
  S('Frontheben (Kurzhantel)', ['schultern'], 'Front Raise, Frontheben, vordere Schulter, Vorheben'),
  S('Frontheben (Kabel)', ['schultern'], 'Cable Front Raise, Kabel Frontheben, Frontheber Kabel'),
  S('Reverse Butterfly (Maschine)', ['schultern', 'oberer_ruecken'], 'Reverse Pec Deck, Rear Delt Maschine, hintere Schulter Maschine, Butterfly Reverse, Reverse Fly Maschine'),
  S('Aufrechtes Rudern', ['schultern', 'oberer_ruecken'], 'Upright Row, Aufrechtrudern, Kinn-Rudern, Stange zum Kinn'),
  S('Schulterheben (Kurzhantel)', ['oberer_ruecken'], 'Shrugs, Dumbbell Shrug, Nackenheben, Trapezheben, Schulterzucken Kurzhantel'),
  S('Schulterheben (Langhantel)', ['oberer_ruecken'], 'Barbell Shrug, Shrugs Langhantel, Trapez Langhantel, Nackenheben Stange'),
  S('Schulterheben (Maschine)', ['oberer_ruecken'], 'Shrug Maschine, Trapezmaschine, Trapez Maschine, Nackenmaschine'),
  S('Handstand-Liegestütze', ['schultern', 'trizeps'], 'Handstand Push Ups, HSPU, Handstandpushups, Kopfstand Drücken'),

  // ---- Rücken ----
  S('Klimmzüge (Untergriff)', ['lat', 'bizeps'], 'Chin Ups, Chinups, Untergriff Klimmzug, Klimmzüge eng Untergriff'),
  S('Klimmzüge (breiter Griff)', ['lat'], 'Wide Grip Pull Ups, weite Klimmzüge, breite Klimmzüge'),
  S('Klimmzüge (neutraler Griff)', ['lat', 'bizeps'], 'Neutral Grip Pull Ups, Hammergriff Klimmzüge, paralleler Griff Klimmzug'),
  S('Klimmzug-Maschine (unterstützt)', ['lat'], 'Assisted Pull Up, Gravitron, Klimmzugmaschine, Klimmzug Hilfe, Klimmzughilfe Maschine'),
  S('Latziehen (enger Griff)', ['lat', 'bizeps'], 'Close Grip Pulldown, V-Griff Latzug, enger Latzug, Latzug eng'),
  S('Latziehen (Untergriff)', ['lat', 'bizeps'], 'Underhand Pulldown, Latzug Untergriff, Reverse Grip Pulldown'),
  S('Latziehen (einarmig)', ['lat'], 'Single Arm Pulldown, einarmiger Latzug, Latzug einarmig Kabel'),
  S('Latziehen zum Nacken', ['lat', 'schultern'], 'Behind The Neck Pulldown, Nackenziehen, Latzug hinter den Kopf'),
  S('Geradarm-Latziehen (Kabel)', ['lat'], 'Straight Arm Pulldown, Stiff Arm Pulldown, Lat Pushdown, Armstrecken Kabel Lat'),
  S('Rudern (Maschine, Brustpolster)', ['oberer_ruecken', 'lat'], 'Chest Supported Row Maschine, Rudermaschine, Row Maschine, Rudern an der Maschine'),
  S('Rudern (T-Stange)', ['oberer_ruecken', 'lat'], 'T-Bar Row, T Bar Rudern, T-Stangen Rudern, Landmine Rudern'),
  S('Kurzhantelrudern (einarmig)', ['lat', 'oberer_ruecken'], 'One Arm Dumbbell Row, Einarmiges Rudern, KH Rudern, Rudern auf Bank, Rudern einarmig'),
  S('Rudern (Kurzhantel, Schrägbank)', ['oberer_ruecken', 'lat'], 'Chest Supported Dumbbell Row, Rudern bäuchlings, Incline Row, Seal Row'),
  S('Rudern (Smith-Maschine)', ['oberer_ruecken', 'lat'], 'Smith Machine Row, Multipresse Rudern'),
  S('Rudern (Untergriff, Langhantel)', ['lat', 'bizeps'], 'Underhand Barbell Row, Yates Row, Rudern Untergriff, Reverse Grip Row'),
  S('Pendlay Row', ['oberer_ruecken', 'lat'], 'Pendlay Rudern, Rudern vom Boden, Explosives Rudern'),
  S('Kabelrudern (einarmig)', ['lat', 'oberer_ruecken'], 'Single Arm Cable Row, einarmig Kabel Rudern, einarmiges Kabelrudern'),
  S('Kabelrudern (breiter Griff)', ['oberer_ruecken'], 'Wide Grip Cable Row, Rudern breit, breites Kabelrudern, hintere Schulter Rudern'),
  S('Hyperextensions', ['unterer_ruecken', 'gesaess'], 'Rückenstrecker, Back Extension, Rückenstrecken, Hyper, Hyperextension Bank, Römischer Stuhl'),
  S('Rückenstrecker (Maschine)', ['unterer_ruecken'], 'Back Extension Maschine, Lower Back Maschine, Rückenmaschine, Rumpfstrecker'),
  S('Good Mornings', ['unterer_ruecken', 'beinbeuger'], 'Good Morning, Gute Morgen, Langhantel Beugen Rücken'),
  S('Sumo-Kreuzheben', ['gesaess', 'beinbeuger'], 'Sumo Deadlift, Sumo, breites Kreuzheben, Sumo Heben'),
  S('Trap-Bar-Kreuzheben', ['quadrizeps', 'gesaess'], 'Hex Bar Deadlift, Trapbar Kreuzheben, Sechskantstange, Hex Bar'),
  S('Kreuzheben (Smith-Maschine)', ['unterer_ruecken', 'gesaess'], 'Smith Machine Deadlift, Multipresse Kreuzheben'),
  S('Rack Pull', ['unterer_ruecken', 'oberer_ruecken'], 'Rack Pulls, Kreuzheben aus dem Rack, Block Pull, Teilkreuzheben'),
  S('Kurzhantel-Kreuzheben', ['gesaess', 'beinbeuger'], 'Dumbbell Deadlift, KH Kreuzheben, Kreuzheben mit Kurzhanteln'),
  S('Superman', ['unterer_ruecken'], 'Rückenheben, Back Raise Boden, Rücken Boden, Rückenstrecken liegend'),
  S('Seilzug-Pullover', ['lat'], 'Cable Pullover, Kabelpullover, Seilzug Überzüge'),
  S('Inverted Rows', ['oberer_ruecken', 'lat'], 'Australian Pull Ups, Körpergewicht Rudern, Rudern unter Stange, Invertiertes Rudern, TRX Rudern'),
  S('Face Pulls (Seil, hoch)', ['schultern', 'oberer_ruecken'], 'Rope Face Pull, Seil Facepulls, Facepull hoch, Face Pulls Seil'),

  // ---- Bizeps ----
  S('Bizepscurls (Kurzhantel)', ['bizeps'], 'Dumbbell Curl, KH Curls, Kurzhantel Curl, Wechselcurls, Alternating Curl'),
  S('Bizepscurls (Maschine)', ['bizeps'], 'Biceps Curl Maschine, Bizepsmaschine, Curlmaschine, Bizeps Maschine sitzend'),
  S('Scott-Curls (Maschine)', ['bizeps'], 'Preacher Curl Maschine, Preacher Curl, Scott Curl Maschine, Bizepsmaschine Preacher, Scottbank Maschine'),
  S('Scott-Curls (Langhantel)', ['bizeps'], 'Preacher Curl Langhantel, Scottcurls, Scottbank, Scott Curl SZ-Stange, Preacher Bar'),
  S('Scott-Curls (Kurzhantel)', ['bizeps'], 'Preacher Curl Kurzhantel, einarmig Scottbank, Scottbank Kurzhantel'),
  S('Bizepscurls (Kabel)', ['bizeps'], 'Cable Curl, Kabelcurls, Kabel Bizeps, Zugturm Curls, Curl am Kabel'),
  S('Bizepscurls (Seil, Kabel)', ['bizeps'], 'Rope Hammer Curl Kabel, Seil Curls, Hammer Curl Kabel, Seil Hammercurls'),
  S('Konzentrationscurls', ['bizeps'], 'Concentration Curl, Konzentrations Curl, Curl sitzend am Knie'),
  S('Schrägbank-Curls', ['bizeps'], 'Incline Dumbbell Curl, Incline Curl, Curls auf Schrägbank, langer Bizepskopf'),
  S('Spider Curls', ['bizeps'], 'Spider Curl, Curl bäuchlings, Bizeps Schrägbank Bauch'),
  S('Langhantel-Curls (enger Griff)', ['bizeps'], 'Close Grip Curl, enge Curls, Curls eng'),
  S('Reverse Curls', ['bizeps'], 'Reverse Curl, Umgekehrte Curls, Obergriff Curls, Unterarm Curls Langhantel, Brachialis'),
  S('Zottman Curls', ['bizeps'], 'Zottman Curl, Drehcurls, Curl hoch Hammer runter'),
  S('Drag Curls', ['bizeps'], 'Drag Curl, Curls an Körper entlang, Zugcurls'),
  S('Handgelenkcurls', ['bizeps'], 'Wrist Curl, Unterarm Curls, Unterarmtraining, Unterarmbeuger'),

  // ---- Trizeps ----
  S('Trizepsdrücken (Seil)', ['trizeps'], 'Rope Pushdown, Seildrücken, Trizeps Seil, Pushdown Seil, Seilzug Trizeps'),
  S('Trizepsdrücken (Stange, Kabel)', ['trizeps'], 'Pushdown Stange, V-Stange Trizeps, gerade Stange Pushdown, Trizeps Stange Kabel'),
  S('Trizepsdrücken (einarmig, Kabel)', ['trizeps'], 'Single Arm Pushdown, einarmig Trizeps, einarmiges Trizepsdrücken'),
  S('Trizepsdrücken (Untergriff, Kabel)', ['trizeps'], 'Reverse Grip Pushdown, Untergriff Pushdown, Trizeps Untergriff'),
  S('Überkopf-Trizepsstrecken (Kabel)', ['trizeps'], 'Overhead Triceps Extension Cable, Trizeps über Kopf Kabel, Overhead Extension Seil, Trizepsstrecken überkopf'),
  S('Überkopf-Trizepsstrecken (Kurzhantel)', ['trizeps'], 'Overhead Dumbbell Extension, Trizeps über Kopf Kurzhantel, Nackendrücken Kurzhantel, Trizepsstrecken sitzend'),
  S('Trizepsmaschine', ['trizeps'], 'Triceps Extension Maschine, Trizeps Maschine, Trizepsdrücken Maschine, Dip Maschine Trizeps'),
  S('Enges Bankdrücken', ['trizeps', 'brust'], 'Close Grip Bench Press, Schmales Bankdrücken, Trizeps Bankdrücken, enges Drücken'),
  S('French Press (Kurzhantel)', ['trizeps'], 'Dumbbell Skull Crusher, Stirndrücken Kurzhantel, liegendes Trizepsstrecken Kurzhantel'),
  S('French Press (Kabel)', ['trizeps'], 'Cable Skull Crusher, Kabel Stirndrücken, liegend Kabel Trizeps'),
  S('Trizeps-Kickbacks', ['trizeps'], 'Triceps Kickback, Kickbacks Kurzhantel, Rückschwung Trizeps, Trizeps Rückstoß'),
  S('Bankdrücken (Trizeps-Fokus, Smith-Maschine)', ['trizeps', 'brust'], 'Smith Machine Close Grip Bench, enges Bankdrücken Smith'),
  S('Bank-Dips', ['trizeps'], 'Bench Dips, Dips an der Bank, Trizeps Dips Bank, Stuhl Dips'),
  S('Diamant-Liegestütze', ['trizeps', 'brust'], 'Diamond Push Ups, enge Liegestütze, Trizeps Liegestütze, Diamond Pushups'),

  // ---- Beine / Gesäß ----
  S('Kniebeuge (Frontkniebeuge)', ['quadrizeps', 'gesaess'], 'Front Squat, Frontkniebeugen, Front Kniebeuge, Frontbeuge'),
  S('Kniebeuge (Smith-Maschine)', ['quadrizeps', 'gesaess'], 'Smith Machine Squat, Multipresse Kniebeuge, Smith Kniebeugen'),
  S('Kniebeuge (Kurzhantel, Goblet)', ['quadrizeps', 'gesaess'], 'Goblet Squat, Goblet Kniebeuge, Kelchkniebeuge, Kniebeuge mit Kurzhantel vor der Brust'),
  S('Hackenschmidt-Kniebeuge (Maschine)', ['quadrizeps', 'gesaess'], 'Hack Squat, Hackenschmidt, Hack Squat Maschine, Hackmaschine'),
  S('Kniebeuge (Maschine)', ['quadrizeps', 'gesaess'], 'Squat Maschine, Kniebeugenmaschine, Pendulum Squat, V-Squat, Belt Squat'),
  S('Kniebeuge (Körpergewicht)', ['quadrizeps', 'gesaess'], 'Air Squat, Bodyweight Squat, Kniebeugen ohne Gewicht, Squats Körpergewicht'),
  S('Bulgarische Kniebeuge', ['quadrizeps', 'gesaess'], 'Bulgarian Split Squat, Split Squat Bank, Bulgarian, Ausfallschritt hinten erhöht'),
  S('Ausfallschritte (Kurzhantel)', ['quadrizeps', 'gesaess'], 'Dumbbell Lunges, Lunges Kurzhantel, KH Ausfallschritte, Walking Lunges Kurzhantel'),
  S('Ausfallschritte rückwärts', ['quadrizeps', 'gesaess'], 'Reverse Lunges, Rückwärts Lunges, Rückwärtsausfallschritt, Ausfallschritt zurück'),
  S('Seitliche Ausfallschritte', ['quadrizeps', 'gesaess'], 'Lateral Lunge, Side Lunge, Seitliche Lunges, Seitausfallschritt'),
  S('Step-ups', ['quadrizeps', 'gesaess'], 'Step Up, Aufsteiger, Stufen steigen, Box Step Ups, Kasten Step Ups'),
  S('Sissy Squat', ['quadrizeps'], 'Sissy Squats, Sissy Kniebeuge, Quadrizeps Kniebeuge zurücklehnen'),
  S('Beinpresse (liegend, 45°)', ['quadrizeps', 'gesaess'], '45 Grad Beinpresse, Leg Press 45, Schräge Beinpresse, Beinpresse schräg'),
  S('Beinpresse (sitzend)', ['quadrizeps', 'gesaess'], 'Seated Leg Press, Horizontale Beinpresse, Beinpresse waagerecht, Beinpresse Maschine sitzend'),
  S('Beinpresse (enge Fußstellung)', ['quadrizeps'], 'Leg Press eng, Beinpresse Füße eng, Quadrizeps Beinpresse'),
  S('Beinpresse (breite Fußstellung)', ['gesaess', 'quadrizeps'], 'Leg Press breit, Beinpresse Füße breit, Gesäß Beinpresse, Beinpresse weit oben'),
  S('Beinstrecker (einbeinig)', ['quadrizeps'], 'Single Leg Extension, einbeiniger Beinstrecker, Beinstrecker einseitig'),
  S('Beinbeuger (sitzend)', ['beinbeuger'], 'Seated Leg Curl, sitzender Beinbeuger, Beinbeuger Maschine sitzend, Leg Curl sitzend'),
  S('Beinbeuger (liegend)', ['beinbeuger'], 'Lying Leg Curl, liegender Beinbeuger, Beinbeuger Maschine liegend, Leg Curl liegend'),
  S('Beinbeuger (stehend, einbeinig)', ['beinbeuger'], 'Standing Leg Curl, stehender Beinbeuger, einbeiniger Beinbeuger stehend'),
  S('Beinbeuger (Kabel)', ['beinbeuger'], 'Cable Leg Curl, Kabel Beinbeuger, Beinbeugen Kabelzug'),
  S('Nordic Curls', ['beinbeuger'], 'Nordic Hamstring Curl, Nordic Hamstring, Beinbeuger Boden, Nordics'),
  S('Rumänisches Kreuzheben (Kurzhantel)', ['beinbeuger', 'gesaess'], 'Dumbbell RDL, KH RDL, Rumänisches mit Kurzhanteln, Kurzhantel Rumänisch'),
  S('Rumänisches Kreuzheben (Smith-Maschine)', ['beinbeuger', 'gesaess'], 'Smith Machine RDL, Multipresse RDL, Rumänisches Smith'),
  S('Einbeiniges Kreuzheben', ['beinbeuger', 'gesaess'], 'Single Leg RDL, einbeiniges RDL, Einbein Kreuzheben, Single Leg Deadlift'),
  S('Hip Thrust (Langhantel)', ['gesaess', 'beinbeuger'], 'Hip Thrusts, Beckenheben, Glute Bridge Langhantel, Gesäßheben, Po Training'),
  S('Hip Thrust (Maschine)', ['gesaess'], 'Hip Thrust Maschine, Glute Drive, Beckenheben Maschine, Gesäßmaschine'),
  S('Hip Thrust (Smith-Maschine)', ['gesaess'], 'Smith Machine Hip Thrust, Multipresse Hip Thrust'),
  S('Glute Bridge', ['gesaess', 'beinbeuger'], 'Gesäßbrücke, Beckenheben Boden, Bridge, Glute Bridges, Brücke'),
  S('Kabel-Kickbacks (Gesäß)', ['gesaess'], 'Glute Kickback, Cable Kickback, Kabel Rückschwung, Gesäß Kabel, Po Kickback'),
  S('Gesäßmaschine (Kickback)', ['gesaess'], 'Glute Kickback Maschine, Kickback Maschine, Po Maschine, Gesäß Maschine stehend'),
  S('Abduktoren (Maschine)', ['gesaess'], 'Hip Abduction, Abduktorenmaschine, Beinspreizer, Beine auseinander Maschine, Außenseite Oberschenkel'),
  S('Adduktoren (Maschine)', ['quadrizeps'], 'Hip Adduction, Adduktorenmaschine, Beine zusammen Maschine, Innenseite Oberschenkel, Beinschließer'),
  S('Seitliches Beinheben', ['gesaess'], 'Side Leg Raise, Beinheben seitlich, Abduktion Boden, Clamshell, Seitlage Beinheben'),
  S('Wadenheben (sitzend)', ['waden'], 'Seated Calf Raise, sitzende Wadenmaschine, Wadenheben Maschine sitzend, Waden sitzend'),
  S('Wadenheben (Beinpresse)', ['waden'], 'Calf Press, Wadenpresse Beinpresse, Waden an der Beinpresse'),
  S('Wadenheben (Smith-Maschine)', ['waden'], 'Smith Machine Calf Raise, Multipresse Waden'),
  S('Wadenheben (einbeinig, Kurzhantel)', ['waden'], 'Single Leg Calf Raise, einbeiniges Wadenheben, Waden einbeinig'),
  S('Wadenheben (Langhantel, stehend)', ['waden'], 'Barbell Calf Raise, Waden Langhantel, Wadenheben Stange'),
  S('Sprünge (Kniebeugesprung)', ['quadrizeps', 'gesaess', 'waden'], 'Jump Squat, Squat Jumps, Hocksprung, Sprungkniebeuge'),
  S('Box Jumps', ['quadrizeps', 'gesaess', 'waden'], 'Boxsprünge, Kastensprünge, Jump auf Box, Plyo Box'),
  S('Wandsitzen', ['quadrizeps'], 'Wall Sit, Wandsitz, Stuhl an der Wand'),
  S('Schlittenschieben', ['quadrizeps', 'gesaess'], 'Sled Push, Prowler, Schlitten, Sled, Schlitten drücken'),
  S('Farmers Walk', ['oberer_ruecken', 'bauch'], 'Farmer Walk, Farmers Carry, Bauernspaziergang, Koffer tragen, Gewichte tragen'),

  // ---- Bauch / Rumpf ----
  S('Beinheben (liegend)', ['bauch'], 'Leg Raise, Beine heben liegend, Beinheber, untere Bauchmuskeln, Lying Leg Raise'),
  S('Beinheben (hängend)', ['bauch'], 'Hanging Leg Raise, hängendes Beinheben, Beinheben Klimmzugstange, Beine heben Reck'),
  S('Knieheben (hängend)', ['bauch'], 'Hanging Knee Raise, Knie heben hängend, Knee Raises, Hängendes Knieheben'),
  S('Knieheben (Römischer Stuhl)', ['bauch'], 'Captain Chair, Knieheben Stuhl, Beinheben Stütz, Vertical Knee Raise'),
  S('Bauchmaschine', ['bauch'], 'Ab Crunch Maschine, Crunch Maschine, Bauchtrainer Maschine, Abdominal Maschine, Bauchpresse Maschine'),
  S('Cable Crunches (Kabel)', ['bauch'], 'Cable Crunch, Kabel Crunch, Kniende Bauchpresse, Seilzug Crunch, Kabelcrunches'),
  S('Sit-ups', ['bauch'], 'Situps, Rumpfbeuge, Aufrichter, Sit Up, Bauchmuskeltraining Boden'),
  S('Bicycle Crunches', ['bauch'], 'Fahrrad Crunches, Radfahren Bauch, Bauch Fahrrad, Bicycle Crunch'),
  S('Russian Twists', ['bauch'], 'Russian Twist, Rumpfdrehen, Russische Drehung, Twists, schräge Bauchmuskeln'),
  S('Mountain Climbers', ['bauch', 'schultern'], 'Bergsteiger, Mountain Climber, Kletterer, Bergsteigerlauf'),
  S('Ab Wheel Rollout', ['bauch'], 'Bauchroller, Ab Roller, Ab Wheel, Rollout, Bauchrad, Roller'),
  S('Seitstütz', ['bauch'], 'Side Plank, seitlicher Unterarmstütz, Seitliche Planke, Seitplank'),
  S('Pallof Press', ['bauch'], 'Pallof, Anti-Rotation Press, Kabel Rumpf Stabi, Pallofpress'),
  S('Woodchopper (Kabel)', ['bauch'], 'Wood Chop, Holzhacker, Kabel Rotation, Cable Chop, Holzfäller'),
  S('Windshield Wipers', ['bauch'], 'Scheibenwischer, Beine seitlich kippen, Windscreen Wipers, Hängend Scheibenwischer'),
  S('Hollow Hold', ['bauch'], 'Hollow Body, Hohlkreuz Halten, Banane halten, Bananenhalte, Hollow Body Hold'),
  S('Dead Bug', ['bauch'], 'Dead Bugs, toter Käfer, Rumpfstabi Rücken, Käfer'),
  S('Bauchmuskeln (Schrägbank)', ['bauch'], 'Decline Sit Ups, Decline Crunch, Negativ Sit Ups, Bauch Schrägbank, Bauchbank'),
  S('Toes to Bar', ['bauch', 'lat'], 'Zehen zur Stange, T2B, Füße zur Stange, Toes To Bar'),
  S('Rückenstrecker (Boden)', ['unterer_ruecken'], 'Bird Dog, Vierfüßler, Rückenstrecken Boden'),

  // ---- Ganzkörper / Funktionell ----
  S('Kettlebell Swing', ['gesaess', 'beinbeuger'], 'KB Swing, Kettlebell Schwung, Swings, Russian Swing, Kugelhantel Schwung'),
  S('Clean (Langhantel)', ['oberer_ruecken', 'quadrizeps', 'gesaess'], 'Power Clean, Hang Clean, Umsetzen, Reißen, Olympisches Gewichtheben, Clean and Jerk'),
  S('Burpees', ['brust', 'quadrizeps'], 'Burpee, Hampelmann Liegestütz, Burpees Ganzkörper, Liegestütz Sprung'),
  S('Thruster', ['quadrizeps', 'schultern'], 'Thrusters, Kniebeuge mit Drücken, Squat to Press, Kurzhantel Thruster'),
  S('Turkish Get-up', ['schultern', 'bauch'], 'Türkisches Aufstehen, TGU, Get Up, Aufstehen mit Gewicht'),
  S('Battle Ropes', ['schultern', 'bauch'], 'Kampfseile, Battle Rope, Schlagseil, Seile schwingen, Tau Training'),

  // ---- Cardio ----
  C('Spinning', 'Indoor Cycling, Spinning Rad, Radkurs, Cycling Kurs'),
  C('Radfahren (draußen)', 'Fahrrad, Rennrad, Mountainbike, Biken, Radtour, Fahrradfahren'),
  C('Schwimmen', 'Bahnen schwimmen, Kraulen, Brustschwimmen, Schwimmbad, Swimming'),
  C('Seilspringen', 'Jump Rope, Rope Skipping, Springseil, Seilchen, Skipping Rope'),
  C('Gehen (Spaziergang)', 'Walking, Spazieren, Wandern, Gehen, Nordic Walking, Walk'),
  C('Treppensteigen', 'Treppe laufen, Treppen, Stairs, Stufen'),
  C('Ski-Ergometer', 'SkiErg, Ski Erg, Skier, Langlauf Maschine'),
  C('Air Bike (Assault Bike)', 'Assault Bike, Airbike, Echo Bike, Fan Bike, Luftwiderstand Rad'),
  C('HIIT (Intervalltraining)', 'High Intensity, Intervalle, Tabata, Zirkeltraining, Cardio Intervall'),
  C('Boxen (Sandsack)', 'Boxsack, Boxtraining, Sandsack, Punching Bag, Kickboxen, Shadowboxing'),
  C('Elliptical-Stepper (Vario)', 'Vario Maschine, Adaptive Motion Trainer, AMT, Ellipsenstepper'),

  // ---- weitere Übungen: Brust ----
  S('Kurzhantel-Schrägbankdrücken (neutraler Griff)', ['brust', 'schultern'], 'Incline Dumbbell Press neutral, Hammergriff Schrägbank, KH Schrägbank neutral'),
  S('Floor Press (Langhantel)', ['brust', 'trizeps'], 'Bodendrücken, Floor Press, Drücken am Boden, Liegend am Boden Stange'),
  S('Bankdrücken (Reverse Grip)', ['brust', 'trizeps'], 'Reverse Grip Bench, Untergriff Bankdrücken, umgekehrter Griff'),
  S('Brustpresse (Kabel, stehend)', ['brust', 'trizeps'], 'Standing Cable Chest Press, Kabel Brustpresse, Kabeldrücken stehend'),
  S('Brustfliegende (Kabel, einarmig)', ['brust'], 'Single Arm Cable Fly, einarmiger Cable Fly, Kabel Fly einarmig'),
  S('Svend Press', ['brust'], 'Plate Squeeze, Scheiben drücken, Svend, Brustquetschen Scheibe'),
  S('Liegestütze (Knie)', ['brust', 'trizeps'], 'Knee Push Ups, Liegestütze auf Knien, leichte Liegestütze, Anfänger Liegestütze'),
  S('Archer-Liegestütze', ['brust', 'trizeps'], 'Archer Push Ups, Bogenschützen Liegestütze, einarmige Liegestütze Seite'),
  // Schultern
  S('Seitheben (Kurzhantel, sitzend)', ['schultern'], 'Seated Lateral Raise, sitzendes Seitheben, Seitheben auf Bank'),
  S('Seitheben (Kabel, einarmig, hinter dem Körper)', ['schultern'], 'Behind Back Cable Lateral Raise, Kabel Seitheben hinten, einarmig hinter dem Rücken'),
  S('Frontheben (Scheibe)', ['schultern'], 'Plate Front Raise, Scheibe heben, Hantelscheibe vorne heben'),
  S('Frontheben (Langhantel)', ['schultern'], 'Barbell Front Raise, Stange frontheben, Langhantel vorne heben'),
  S('Z-Press', ['schultern', 'trizeps'], 'Z Press, Schulterdrücken im Sitzen am Boden, Boden Schulterdrücken'),
  S('Schulterdrücken (Kurzhantel, einarmig)', ['schultern', 'trizeps'], 'Single Arm Dumbbell Press, einarmiges Schulterdrücken, einarmig drücken'),
  S('Y-Heben', ['schultern', 'oberer_ruecken'], 'Y Raise, Y-Raises, Y heben, untere Trapez, Schulterblatt Y'),
  S('Kabel-Schulterdrücken', ['schultern', 'trizeps'], 'Cable Shoulder Press, Kabel Overhead Press, Schulterdrücken Kabel'),
  // Rücken
  S('Meadows Row', ['lat', 'oberer_ruecken'], 'Meadows Rudern, Landmine Einarm Rudern, Landmine Row einarmig'),
  S('Seal Row', ['oberer_ruecken', 'lat'], 'Seal Rudern, Rudern auf der Bank liegend, Bauchlage Rudern, Chest Supported Barbell Row'),
  S('Latziehen (kniend, einarmig, Kabel)', ['lat'], 'Kneeling Single Arm Pulldown, kniender Latzug, Latzug kniend'),
  S('Rudern (Maschine, einarmig)', ['lat', 'oberer_ruecken'], 'Single Arm Row Machine, einarmige Rudermaschine, Hammer Strength Row einarmig'),
  S('Klimmzüge (gewichtet)', ['lat', 'bizeps'], 'Weighted Pull Ups, Klimmzüge mit Gewicht, Klimmzüge mit Gürtel, Dip Gürtel'),
  S('Klimmzüge (Negativ)', ['lat', 'bizeps'], 'Negative Pull Ups, Negativ Klimmzüge, langsam ablassen, Klimmzug Anfänger'),
  S('Rudern am Kabel (Seil zum Hals)', ['oberer_ruecken', 'schultern'], 'Rope Row To Neck, Seil Rudern Hals, Kabel Face Row, Rudern zum Hals'),
  S('Hyperextensions (gewichtet)', ['unterer_ruecken', 'gesaess'], 'Weighted Back Extension, Rückenstrecker mit Gewicht, Hyper mit Scheibe'),
  S('Reverse Hyperextension', ['unterer_ruecken', 'gesaess'], 'Reverse Hyper, umgekehrter Rückenstrecker, Reverse Hyper Maschine'),
  S('Good Mornings (sitzend)', ['unterer_ruecken'], 'Seated Good Morning, sitzende Good Mornings, Good Morning Sitzend'),
  // Bizeps
  S('Bizepscurls (SZ-Stange)', ['bizeps'], 'EZ Bar Curl, SZ Curls, SZ Stange Curl, Curlstange, Curl mit SZ'),
  S('Cross-Body Hammercurls', ['bizeps'], 'Cross Body Hammer Curl, Hammer quer vor dem Körper, Hammercurl quer'),
  S('21er Curls', ['bizeps'], '21s Curls, 21er, Dreimal Sieben Curls, Siebener Curls'),
  S('Scott-Curls (SZ-Stange)', ['bizeps'], 'EZ Bar Preacher Curl, Scottcurl SZ, Preacher SZ Stange'),
  S('Bizepscurls (Kabel, beidarmig, hoch)', ['bizeps'], 'High Cable Curl, Double Biceps Cable, Kabel Doppel Bizeps, Bizepspose Kabel'),
  S('Bizepscurls (Maschine, einarmig)', ['bizeps'], 'Single Arm Curl Machine, einarmige Bizepsmaschine'),
  S('Hammercurls (Schrägbank)', ['bizeps'], 'Incline Hammer Curl, Hammer Schrägbank, Schrägbank Hammer'),
  S('Kabelcurls (liegend)', ['bizeps'], 'Lying Cable Curl, liegende Kabelcurls, Kabel Curl am Boden'),
  // Trizeps
  S('Trizepsdrücken (V-Griff)', ['trizeps'], 'V Bar Pushdown, V Griff, V Stange Pushdown, Trizeps V-Stange'),
  S('Trizeps-Kickbacks (Kabel)', ['trizeps'], 'Cable Triceps Kickback, Kabel Kickback Trizeps, Kickback am Kabel'),
  S('JM Press', ['trizeps', 'brust'], 'JM-Press, JM Drücken, Trizeps Bankdrücken Mix, Smith JM Press'),
  S('Überkopf-Trizepsstrecken (einarmig, Kurzhantel)', ['trizeps'], 'Single Arm Overhead Triceps Extension, einarmig Nackendrücken, einarmiges Trizepsstrecken'),
  S('Close-Grip Liegestütze', ['trizeps', 'brust'], 'Triceps Push Ups, enge Liegestütze, Trizeps Liegestütze, Close Grip Pushup'),
  S('Tate Press', ['trizeps'], 'Tate Presse, Ellbogen Hanteln zur Brust, Trizeps Hantel Liegend'),
  // Beine
  S('Kniebeuge (Box Squat)', ['quadrizeps', 'gesaess'], 'Box Squats, Kniebeugen auf Kasten, Box Kniebeuge, Kniebeuge mit Bank'),
  S('Zercher-Kniebeuge', ['quadrizeps', 'gesaess'], 'Zercher Squat, Kniebeuge Ellbogenbeuge, Zercher'),
  S('Kniebeuge (Pause)', ['quadrizeps', 'gesaess'], 'Pause Squat, Kniebeuge mit Pause, Pausenkniebeuge, Pause unten'),
  S('Pistol Squat (unterstützt)', ['quadrizeps', 'gesaess'], 'Einbeinige Kniebeuge, Pistol Kniebeuge, einbeinige Kniebeugen, Einbein Squat'),
  S('Ausfallschritte (gehend, Langhantel)', ['quadrizeps', 'gesaess'], 'Barbell Walking Lunges, Walking Lunges Stange, gehende Ausfallschritte'),
  S('Ausfallschritte (Smith-Maschine)', ['quadrizeps', 'gesaess'], 'Smith Machine Lunges, Multipresse Ausfallschritt, Smith Lunges'),
  S('Curtsy Lunge', ['gesaess', 'quadrizeps'], 'Curtsy Lunges, Knicks Ausfallschritt, Überkreuz Ausfallschritt, Knicks Lunge'),
  S('Beinpresse (einbeinig)', ['quadrizeps', 'gesaess'], 'Single Leg Press, einbeinige Beinpresse, Beinpresse eine Seite'),
  S('Beinbeuger (einbeinig, liegend)', ['beinbeuger'], 'Single Leg Curl Lying, einbeiniger Beinbeuger liegend, Leg Curl einbeinig liegend'),
  S('Wadenheben (Esel)', ['waden'], 'Donkey Calf Raise, Eselwaden, Donkey Waden, Wadenheben vorgebeugt'),
  S('Wadenheben (Hackenschmidt-Maschine)', ['waden'], 'Hack Squat Calf Raise, Waden Hack Maschine, Waden Hack'),
  S('Sumo-Kniebeuge (Kurzhantel)', ['quadrizeps', 'gesaess'], 'Sumo Squat Dumbbell, breite Kniebeuge Kurzhantel, Plié Squat'),
  S('Seitliches Beinheben (Kabel)', ['gesaess'], 'Cable Hip Abduction, Kabel Abduktion, Seitheben Bein Kabel, Kabel Beinabspreizen'),
  S('Frog Pumps', ['gesaess'], 'Frosch Pumps, Froschpumpen, Glute Bridge Frosch, Beine Frosch Hüftheben'),
  S('Hip Thrust (einbeinig)', ['gesaess', 'beinbeuger'], 'Single Leg Hip Thrust, einbeiniger Hip Thrust, Einbein Hip Thrust'),
  S('Cable Pull-Through (Kabel)', ['gesaess', 'beinbeuger'], 'Pull Through, Kabel Pull Through, Hüftbeuge Kabel, Kabel Hüftstrecken stehend'),
  S('Kniebeuge (Landmine)', ['quadrizeps', 'gesaess'], 'Landmine Squat, Landmine Kniebeuge, Kniebeuge mit Landmine'),
  S('Wadenheben (einbeinig, Maschine)', ['waden'], 'Single Leg Calf Machine, einbeiniges Wadenheben Maschine'),
  // Rumpf
  S('Bauchrad (kniend)', ['bauch'], 'Kneeling Ab Wheel, Bauchroller Knie, Ab Roller kniend, Rollout Knie'),
  S('V-Ups', ['bauch'], 'V Ups, Taschenmesser, Jackknife, V-Sit Ups, Klappmesser Bauch'),
  S('Flutter Kicks', ['bauch'], 'Scherenschläge, Beine flattern, Bauch Schere, Flatterschlag'),
  S('Heel Taps', ['bauch'], 'Fersen tippen, Heel Touch, Seitliche Crunches Boden, Fersentouch'),
  S('Reverse Crunch', ['bauch'], 'Umgekehrter Crunch, Becken heben Bauch, Reverse Crunches, unterer Bauch Crunch'),
  S('Seitstütz mit Beinheben', ['bauch', 'gesaess'], 'Side Plank Leg Raise, Seitplank Beinheben, Seitstütz Bein'),
  S('Bear Crawl', ['bauch', 'schultern'], 'Bärengang, Bear Walk, Krabbeln, Bärenkrabbeln, Krabbelgang'),
  S('Hollow Rock', ['bauch'], 'Hohlkörper Schaukel, Hollow Body Rock, Banane schaukeln, Hollow Schaukel'),
  S('Bauchrolle (Kabel, kniend)', ['bauch'], 'Kabel Rollout, Abdominal Cable Rollout, Kabelzug Bauch kniend, Kabel Crunch lang'),
  // Funktionell
  S('Kettlebell Snatch', ['schultern', 'gesaess'], 'KB Snatch, Kettlebell Reißen, einarmiges Reißen, Snatch Kugelhantel'),
  S('Kettlebell Clean & Press', ['schultern', 'gesaess'], 'KB Clean and Press, Kettlebell Umsetzen und Drücken, Clean Press Kettlebell'),
  S('Medizinball Wandwurf', ['quadrizeps', 'schultern'], 'Wall Ball, Wallballs, Medizinball werfen, Ball an die Wand, Wandball'),
  S('Slam Ball', ['schultern', 'bauch'], 'Slam Balls, Ball auf Boden schmettern, Sandball Slam, Medizinball Slam'),
  S('Suitcase Carry', ['bauch', 'oberer_ruecken'], 'Koffer tragen einseitig, Einhand Farmers Walk, Einseitiges Tragen, Suitcase'),
  S('Sled Pull (Schlitten ziehen)', ['quadrizeps', 'gesaess'], 'Schlitten ziehen, Sled Drag, Prowler Pull, Rückwärts Schlitten ziehen'),
  S('Reifen kippen', ['quadrizeps', 'gesaess', 'oberer_ruecken'], 'Tire Flip, Reifenkippen, Traktorreifen heben, Reifen drehen'),
  S('Seilklettern', ['lat', 'bizeps'], 'Rope Climb, Tau klettern, Tauklettern, Klettertau'),
  S('Trap-Bar-Schulterheben', ['oberer_ruecken'], 'Trap Bar Shrug, Hex Bar Shrug, Schulterheben Trap Bar, Trapezheben Hex'),

  // ---- Cardio und Sportarten ----
  C('Joggen (Intervall)', 'Intervalllauf, Intervall Joggen, Fartlek, Tempowechsel, Intervall laufen'),
  C('Sprints', 'Sprint, Sprinten, Antritte, Steigerungsläufe, Sprintintervalle, Läufe schnell'),
  C('Berglauf', 'Hügellauf, Hill Run, Bergauf laufen, Hill Sprints, Anstieg laufen, Berg laufen'),
  C('Treppenlauf (draußen)', 'Stairs Run, Treppensprint, Treppen rennen, Stadion Treppen, Stufenlauf'),
  C('Nordic Walking', 'Walking mit Stöcken, Stockwandern, Nordic Walk, Stöcke gehen'),
  C('Wandern (Berg)', 'Bergwandern, Hiking, Bergtour, Trekking, Gipfel Wanderung, Wandertour'),
  C('Radfahren (Intervall)', 'Radintervalle, Fahrrad Intervalle, Bike HIIT, Radtraining Intervall, Tempo Rad'),
  C('Mountainbike', 'MTB, Mountainbiken, Geländerad, Trail Bike, Bergradeln, Offroad Rad'),
  C('Rennrad', 'Road Bike, Rennradfahren, Rennradtour, Straßenrad, Rennradausfahrt'),
  C('Rudergerät (Intervall)', 'Rower Intervall, Ruder Intervalle, Concept2 Intervall, Rudern Intervalle'),
  C('Schwimmen (Kraul)', 'Freistil, Kraulschwimmen, Freistil schwimmen, Crawl, Bahnen kraulen'),
  C('Schwimmen (Brust)', 'Brustschwimmen, Brust schwimmen, Brustbahnen, Schwimmen gemütlich'),
  C('Aqua-Jogging', 'Wasserlaufen, Aqua Running, Aquajogging, Laufen im Wasser, Aqua Fitness'),
  C('Feldhockey', 'Hockey, Feld Hockey, Hockey Training, Hockeyspiel, Hockey Match, Rasenhockey'),
  C('Tennis', 'Tennis spielen, Tennistraining, Tennismatch, Einzel Tennis, Doppel Tennis, Tennis Match'),
  C('Fußball', 'Fussball, Kicken, Fußballtraining, Fußballspiel, Bolzen, Soccer, Kicken gehen'),
  C('Basketball', 'Basketball spielen, Basketballtraining, Streetball, Korbleger, Basketball Match'),
  C('Handball', 'Handball spielen, Handballtraining, Handballspiel, Handball Match'),
  C('Volleyball', 'Volleyball spielen, Beachvolleyball, Volleyballtraining, Beach Volleyball'),
  C('Badminton', 'Federball, Badminton spielen, Badmintontraining, Badminton Match'),
  C('Tischtennis', 'Tischtennis spielen, Ping Pong, Tischtennistraining, TT Spiel'),
  C('Squash', 'Squash spielen, Squashtraining, Squash Match, Squashhalle'),
  C('Klettern (Halle)', 'Bouldern, Kletterhalle, Boulder, Sportklettern, Klettern Halle, Indoor Klettern'),
  C('Kampfsport (Training)', 'Kickboxen, MMA, Karate, Judo, Taekwondo, Muay Thai, Thaiboxen, Brazilian Jiu Jitsu, BJJ, Ringen'),
  C('Tanzen', 'Zumba, Tanzkurs, Hip Hop Tanz, Dance Workout, Standardtanz, Salsa, Tanzfitness'),
  C('Yoga', 'Yoga Stunde, Hatha Yoga, Vinyasa, Power Yoga, Yogakurs, Yoga Flow'),
  C('Pilates', 'Pilates Stunde, Matten Pilates, Pilateskurs, Reformer Pilates'),
  C('Skifahren / Snowboard', 'Ski fahren, Ski Abfahrt, Snowboarden, Skitag, Piste, Wintersport, Skitour'),
  C('Langlauf (Ski)', 'Skilanglauf, Langlaufen, Loipe, Skating Langlauf, klassischer Langlauf'),
  C('Inlineskaten', 'Skaten, Inliner, Rollerblades, Skating, Rollschuh, Inline Skating'),
  C('Eislaufen', 'Schlittschuhlaufen, Eishockey, Schlittschuh, Eisbahn, Eislauf, Eiskunstlauf'),
  C('Golf', 'Golfen, Golf spielen, Driving Range, Golfrunde, 18 Loch'),
  C('Crosstrainer (Intervall)', 'Cross Trainer Intervall, Ellipsentrainer Intervall, Elliptical Intervall, Crosstrainer HIIT'),
  C('Stepper (Intervall)', 'Stairmaster Intervall, Treppenmaschine, Stepper HIIT, Stair Climber Intervall'),
];

/** Stichwörter einer Übung (leer für eigene Übungen) */
const KEYWORDS = new Map(CATALOG.map((c) => [c.name.toLowerCase(), c.keywords]));
export const keywordsOf = (name: string): string => KEYWORDS.get(name.toLowerCase()) ?? '';

/** Muskeln der Standardübungen, nach Namen */
export const CATALOG_MUSCLES: Record<string, MuscleId[]> = Object.fromEntries(CATALOG.filter((c) => c.type === 'strength').map((c) => [c.name, c.muscles]));
