// Weitere Lebensmittel (Varianten) für foodDb.ts – gleiche Zeilenform: [Schlüssel, Name, Aliase (|), kcal, Eiweiß, KH, Fett, Stück-g?, Dichte?, EL-g?]
import type { Row } from './foodDb';

export const ROWS_MORE: Row[] = [
  // Joghurt, Quark, Milch & Co.
  ['joghurt-01', 'Joghurt (0,1 %)', 'joghurt 0,1|joghurt entrahmt|joghurt fettfrei|joghurt 0,1 %', 38, 4.2, 5, 0.1, undefined, 1.03, 18],
  ['joghurt-mild', 'Joghurt mild (3,8 %)', 'joghurt mild|mildes joghurt|ja joghurt|joghurt 3,8', 70, 3.5, 4.7, 4, undefined, 1.03, 18],
  ['fruchtjoghurt', 'Fruchtjoghurt', 'fruchtjoghurt|fruchtjogurt|erdbeerjoghurt|kirschjoghurt|pfirsichjoghurt|heidelbeerjoghurt|bananenjoghurt|joghurt mit frucht', 95, 3.2, 15, 2.5, 150, 1.03, 18],
  ['vanillejoghurt', 'Vanillejoghurt', 'vanillejoghurt|vanille joghurt|joghurt vanille', 100, 3.4, 14.5, 3.3, 150, 1.03, 18],
  ['sojajoghurt', 'Sojajoghurt', 'sojajoghurt|soja joghurt|alpro joghurt|pflanzenjoghurt|veganer joghurt|kokosjoghurt', 45, 3.5, 2.5, 2.2, undefined, 1.03, 18],
  ['proteinjoghurt', 'Proteinjoghurt', 'proteinjoghurt|protein joghurt|high protein joghurt|joghurt protein|eiweissjoghurt|ehrmann high protein', 63, 10, 4.5, 0.5, 200, 1.03, 18],
  ['skyr-frucht', 'Skyr mit Frucht', 'fruchtskyr|skyr frucht|skyr vanille|skyr erdbeere|skyr mit frucht|skyr heidelbeere', 78, 9, 10, 0.2, 150, 1.05, 20],
  ['quark-40', 'Sahnequark (40 %)', 'quark 40|rahmquark|sahnequark 40|quark fett|quark vollfett', 160, 10, 3, 12.5, undefined, 1.05, 20],
  ['fruchtquark', 'Fruchtquark', 'fruchtquark|quark mit frucht|erdbeerquark|quark frucht|obstquark', 102, 8, 13, 2, 150, 1.05, 20],
  ['buttermilch', 'Buttermilch', 'buttermilch|molke|sauermilch|dickmilch', 35, 3.4, 4, 0.5, undefined, 1.03],
  ['kakaomilch', 'Kakaomilch', 'kakaomilch|schokomilch|kakao milch|trinkschokolade|kaba|milch kakao|chocomel', 70, 3.3, 10, 1.8, undefined, 1.03],
  ['magermilch', 'Milch (0,3 %)', 'magermilch|milch 0,3|milch 0,1|entrahmte milch|milch fettfrei|milch mager', 36, 3.4, 4.9, 0.3, undefined, 1.03],
  ['mandeldrink', 'Mandeldrink', 'mandelmilch|mandeldrink|mandel drink|mandel milch', 24, 0.5, 3, 1.1, undefined, 1.03],
  ['kokosmilch', 'Kokosmilch (Dose)', 'kokosmilch|kokosnussmilch|kokos milch|coconut milk', 180, 1.5, 3, 18, undefined, 1],
  ['reisdrink', 'Reisdrink', 'reismilch|reisdrink|reis drink', 49, 0.1, 10, 1, undefined, 1.03],
  ['kondensmilch', 'Kondensmilch (7,5 %)', 'kondensmilch|kaffeesahne|dosenmilch|kaffeemilch', 136, 6.5, 9.5, 8, undefined, 1.05],
  ['pudding', 'Pudding', 'pudding|vanillepudding|schokopudding|milchpudding|griesspudding|dessert', 109, 3, 18, 2.8, 125],
  ['milchreis', 'Milchreis (fertig)', 'milchreis|reisbrei|griessbrei', 118, 3.2, 20, 2.8, 200],
  ['schmand', 'Schmand / Saure Sahne', 'schmand|saure sahne|sauerrahm|sour cream', 200, 3, 3.5, 20, undefined, 1, 20],
  ['creme-fraiche', 'Crème fraîche', 'creme fraiche|cremefraiche|creme fraîche|creme fraiche 30', 292, 2.4, 3, 30, undefined, 1, 20],
  ['mascarpone', 'Mascarpone', 'mascarpone', 410, 4.5, 3.5, 42, undefined, undefined, 20],
  ['ricotta', 'Ricotta', 'ricotta', 161, 8, 3, 13, undefined, undefined, 20],
  // Käse
  ['emmentaler', 'Emmentaler', 'emmentaler|emmentaler kaese|gruyere|bergkaese|appenzeller', 384, 28, 0.5, 30, 25],
  ['edamer', 'Edamer / Tilsiter', 'edamer|tilsiter|butterkaese|maasdamer|leerdammer|gouda jung', 331, 26, 0.5, 25, 25],
  ['cheddar', 'Cheddar', 'cheddar|cheddar kaese|burgerkaese|toastkaese|scheibenkaese', 401, 25, 1, 33, 20],
  ['camembert', 'Camembert / Brie', 'camembert|brie|weichkaese|romadur', 289, 20, 0.5, 23, 30],
  ['halloumi', 'Halloumi', 'halloumi|grillkaese|grillkäse', 321, 22, 2, 25, 40],
  ['schmelzkaese', 'Schmelzkäse', 'schmelzkaese|kaeseecken|streichkaese|schmelzkaeseecke|kaesecreme', 266, 12, 5, 22, 20],
  ['ziegenkaese', 'Ziegenkäse', 'ziegenkaese|ziegenfrischkaese|ziegenfrischkäse|chevre|schafskaese frisch', 274, 18, 1, 22, 30],
  ['kaese-light', 'Käse (fettreduziert)', 'light kaese|kaese light|fettarmer kaese|kaese 30|kaese fettarm|leichter kaese', 248, 30, 0.5, 14, 20],
  ['kaese-reibe', 'Reibekäse', 'reibekaese|geriebener kaese|pizzakaese|kaese gerieben|streukaese', 330, 25, 1, 26, undefined, undefined, 7],
  ['paniertes-kaese', 'Gebackener Käse / Camembert paniert', 'camembert paniert|gebackener kaese|kaesestangen|mozzarella sticks|kaese paniert', 290, 12, 18, 18, 30],
  // Eier & Fleisch
  ['haehnchenbrust-gebraten', 'Hähnchenbrust (gebraten)', 'gebratene haehnchenbrust|haehnchenbrust gebraten|gegrilltes haehnchen|grillhaehnchen|haehnchen gebraten|haehnchenbrust gegart', 156, 31, 0, 3.6],
  ['schweinenacken', 'Schweinenacken / -braten', 'schweinenacken|nackensteak|schweinebraten|schweinesteak|schweinekamm|nacken', 184, 19, 0, 12],
  ['lamm', 'Lamm', 'lamm|lammfleisch|lammkotelett|lammkeule|lammsteak', 220, 19, 0, 16],
  ['leberwurst', 'Leberwurst / Streichwurst', 'leberwurst|streichwurst|teewurst|mettwurst|kalbsleberwurst|schmalzfleisch', 326, 12, 2, 30, undefined, undefined, 15],
  ['gefluegelwurst', 'Geflügelwurst / Putenschinken', 'gefluegelwurst|putenwurst|haehnchenwurst|gefluegelaufschnitt|putenschinken|haehnchenaufschnitt', 113, 16, 1, 5, 15],
  ['leberkaese', 'Leberkäse / Fleischwurst', 'leberkaese|fleischkaese|fleischwurst|lyoner|jagdwurst|mortadella', 290, 12, 2, 26, 100],
  ['frikadelle', 'Frikadelle / Bulette', 'frikadelle|bulette|hackbaellchen|fleischpflanzerl|hacksteak|fleischbaellchen|faschiertes laibchen', 232, 16, 6, 16, 80],
  ['hackfleisch-gemischt', 'Hackfleisch (gemischt)', 'hackfleisch gemischt|gemischtes hack|halb und halb hack|hack gemischt', 250, 17, 0, 20],
  ['schweinehack', 'Hackfleisch (Schwein)', 'schweinehack|schweinehackfleisch|hack schwein', 260, 17, 0, 21],
  ['doener', 'Döner Kebab (mit Brot)', 'doener|doener kebab|kebab|doenerteller|doener tasche|gyros|gyros pita|durum|dürüm', 209, 12, 20, 9, 350],
  ['burger', 'Cheeseburger / Hamburger', 'cheeseburger|hamburger|burger|fast food burger|big mac|whopper|mcdonalds burger', 260, 13, 25, 12, 150],
  ['chicken-nuggets', 'Chicken Nuggets', 'nuggets|chicken nuggets|chickennuggets|haehnchennuggets|chicken mcnuggets', 250, 15, 16, 14, 20],
  ['schnitzel-paniert', 'Schnitzel (paniert)', 'paniertes schnitzel|wiener schnitzel|schnitzel paniert|jaegerschnitzel|cordon bleu|haehnchenschnitzel paniert|schnitzel natur paniert', 246, 17, 13, 14, 150],
  ['entenbrust', 'Ente / Gans', 'entenbrust|gans|gaensebraten|entenkeule', 230, 18, 0, 18],
  ['kassler', 'Kassler / Räucherfleisch', 'kassler|raeucherfleisch|kasseler|geraeuchertes schweinefleisch|eisbein', 200, 22, 0, 12],
  // Fisch
  ['raeucherlachs', 'Räucherlachs', 'raeucherlachs|lachs geraeuchert|graved lachs|lachs aufschnitt|lachsscheiben|raeucherfisch', 178, 22, 0, 10],
  ['makrele', 'Makrele', 'makrele|raeuchermakrele|makrelenfilet', 229, 19, 0, 17],
  ['sardinen', 'Sardinen (Dose)', 'sardinen|sardine|sardellen', 196, 22, 0, 12, 20],
  ['hering', 'Hering / Matjes', 'hering|matjes|bismarckhering|rollmops|heringsfilet|matjesfilet', 198, 18, 0, 14, 40],
  ['thunfisch-oel', 'Thunfisch in Öl', 'thunfisch in oel|oelthunfisch|thunfisch oel|thunfisch mit oel', 199, 25, 0, 11, 120],
  ['surimi', 'Surimi / Krabbenfleisch', 'surimi|krabbenstick|fischstick|krebsfleisch', 90, 8, 10, 1.5, 15],
  ['sushi', 'Sushi (Maki / Nigiri)', 'sushi|maki|nigiri|sushi rolle|sushi set|inside out roll', 149, 6, 28, 1.5, 25],
  ['fischfilet-paniert', 'Fischfilet (paniert)', 'paniertes fischfilet|backfisch|fish and chips|fischfilet paniert|schlemmerfilet', 220, 12, 18, 11, 120],
  ['miesmuscheln', 'Muscheln / Tintenfisch', 'muscheln|miesmuscheln|tintenfisch|calamari|kraken', 80, 14, 3, 1.5],
  // Gemüse & Beilagen
  ['knoblauch', 'Knoblauch', 'knoblauch|knoblauchzehe|knoblauchzehen', 140, 6, 28, 0.5, 4],
  ['radieschen', 'Radieschen / Rettich', 'radieschen|rettich|meerrettich', 15, 1, 2, 0.1, 10],
  ['sellerie', 'Sellerie', 'sellerie|knollensellerie|staudensellerie|stangensellerie', 20, 1.5, 2, 0.3, 40],
  ['fenchel', 'Fenchel', 'fenchel', 31, 1.2, 4, 0.2, 250],
  ['kohlrabi', 'Kohlrabi', 'kohlrabi', 27, 1.7, 3.7, 0.1, 200],
  ['rosenkohl', 'Rosenkohl', 'rosenkohl', 36, 4, 4, 0.5],
  ['weisskohl', 'Weißkohl / Rotkohl', 'weisskohl|rotkohl|blaukraut|krautsalat|spitzkohl|wirsing|kraut', 27, 1.4, 4, 0.2],
  ['chinakohl', 'Chinakohl / Pak Choi', 'chinakohl|pak choi|pak choy|mangold', 13, 1.2, 1.5, 0.2],
  ['spargel', 'Spargel', 'spargel|gruener spargel|weisser spargel', 20, 2.2, 2, 0.1],
  ['kartoffelpueree', 'Kartoffelpüree', 'kartoffelpueree|kartoffelbrei|stampfkartoffeln|kartoffelstampf|pueree', 95, 2, 15, 3],
  ['bratkartoffeln', 'Bratkartoffeln', 'bratkartoffeln|rösti|roesti|haschbraun|kartoffelpuffer|reibekuchen', 131, 2.5, 18, 5.5],
  ['kartoffelsalat', 'Kartoffelsalat', 'kartoffelsalat|nudelsalat|wurstsalat|eiersalat|fleischsalat', 122, 2, 15, 6],
  ['gnocchi', 'Gnocchi / Knödel', 'gnocchi|kloesse|knoedel|kartoffelknoedel|semmelknoedel|serviettenknoedel', 146, 3.5, 32, 0.5, 80],
  ['gurken-eingelegt', 'Gewürzgurken', 'gewuerzgurke|gewuerzgurken|essiggurken|saure gurken|cornichons|eingelegte gurken|pepperoni eingelegt|silberzwiebeln', 15, 0.5, 2.5, 0.1, 30],
  ['gemuese-tk', 'Gemüsemischung (TK)', 'tk gemuese|gemuesemischung|gemuese pfanne|mischgemuese|suppengemuese|gemuese|rahmgemuese|wokgemuese', 40, 2.5, 6, 0.5],
  ['pilze-misch', 'Pilze (Pfifferlinge, Austernpilze …)', 'pfifferlinge|steinpilze|austernpilze|shiitake|kräuterseitlinge|kraeuterseitlinge', 25, 2.5, 3, 0.4],
  ['tomaten-getrocknet', 'Getrocknete Tomaten', 'getrocknete tomaten|tomaten getrocknet|sonnengetrocknete tomaten|tomaten in oel', 213, 14, 35, 3, 5],
  ['ofengemuese', 'Ofengemüse (mit Öl)', 'ofengemuese|gegrilltes gemuese|gebratenes gemuese|pfannengemuese|antipasti gemuese', 80, 2, 8, 4.5],
  // Obst
  ['zitrone', 'Zitrone / Limette', 'zitrone|limette|zitronensaft|limettensaft', 30, 0.7, 6.5, 0.3, 80],
  ['grapefruit', 'Grapefruit', 'grapefruit|pampelmuse|pomelo', 42, 0.8, 9, 0.2, 250],
  ['kirschen', 'Kirschen', 'kirschen|kirsche|sauerkirschen|suesskirschen', 59, 1, 13, 0.3, 8],
  ['pflaumen', 'Pflaumen / Zwetschgen', 'pflaumen|zwetschgen|pflaume|zwetschge|mirabellen|aprikose|aprikosen', 47, 0.6, 10, 0.2, 40],
  ['brombeeren', 'Brombeeren / Johannisbeeren', 'brombeeren|johannisbeeren|stachelbeeren|beeren|beerenmix|waldbeeren|tk beeren', 43, 1.4, 4.9, 0.5],
  ['granatapfel', 'Granatapfel', 'granatapfel|granatapfelkerne', 94, 1.7, 19, 1.2],
  ['feigen', 'Feigen (frisch)', 'feigen|feige|frische feigen|physalis|litschi|papaya|passionsfrucht', 74, 0.8, 16, 0.3, 50],
  ['apfelmus', 'Apfelmus', 'apfelmus|obstmus|fruchtmus|quetschie|fruchtquetschie', 58, 0.3, 14, 0.1],
  ['obstsalat', 'Obstsalat', 'obstsalat|fruchtsalat|obstteller|obstschale', 50, 0.6, 11, 0.2],
  ['cranberries', 'Cranberries (getrocknet)', 'cranberries|trockencranberries|goji|gojibeeren|trockenfruechte mix', 335, 0.5, 82, 1.2],
  ['avocado-halb', 'Avocado (Guacamole)', 'guacamole|avocadocreme|avocado dip', 150, 2, 4, 14, undefined, undefined, 20],
  ['kokosnuss', 'Kokosflocken / Kokosraspel', 'kokosraspel|kokosflocken|kokos|kokosnuss|kokoschips', 600, 6, 8, 60],
  // Brot & Backwaren
  ['dinkelbrot', 'Dinkelbrot', 'dinkelbrot|dinkelvollkornbrot|dinkelmischbrot|kuernerbrot|koernerbrot|mehrkornbrot', 226, 9, 43, 2, 45],
  ['roggenbrot', 'Roggenbrot', 'roggenbrot|roggenmischbrot|bauernbrot|landbrot|pumpernickel|sauerteigbrot', 219, 7, 45, 1.2, 45],
  ['brezel', 'Brezel / Laugenbrötchen', 'brezel|breze|laugenbrezel|laugenbroetchen|laugenstange|laugenbrot|pretzel', 274, 9, 54, 2.5, 70],
  ['croissant', 'Croissant', 'croissant|hoernchen|buttercroissant|plunder|plundergebaeck|blaetterteig|schokocroissant', 401, 8, 45, 21, 60],
  ['vollkornbroetchen', 'Vollkornbrötchen', 'vollkornbroetchen|koernerbroetchen|mehrkornbroetchen|roggenbroetchen|dinkelbroetchen|seelen|sonnenblumenbroetchen', 239, 10, 42, 3.5, 60],
  ['bagel', 'Bagel', 'bagel', 266, 10, 53, 1.5, 90],
  ['pfannkuchen', 'Pfannkuchen / Crêpe', 'pfannkuchen|crepe|crêpe|eierkuchen|palatschinken|pancakes|pancake|kaiserschmarrn', 190, 6, 28, 6, 80],
  ['waffel', 'Waffel', 'waffel|waffeln|belgische waffel|eiswaffel', 327, 6, 42, 15, 60],
  ['donut', 'Donut / Berliner', 'donut|donuts|berliner|krapfen|krapfen|schmalzgebaeck|churros', 378, 6, 48, 18, 70],
  ['kuchen', 'Kuchen (Rührkuchen)', 'kuchen|ruehrkuchen|marmorkuchen|sandkuchen|kaffeekuchen|gugelhupf|stollen|zimtschnecke|streuselkuchen|hefezopf|hefekuchen', 402, 5, 55, 18, 80],
  ['obstkuchen', 'Obstkuchen', 'apfelkuchen|obstkuchen|obsttorte|obstboden|apfelstrudel|strudel|fruchtkuchen|tarte', 219, 3, 35, 7.5, 120],
  ['muffin', 'Muffin / Brownie', 'muffin|muffins|cupcake|brownie|brownies|schokoladenkuchen|schokokuchen', 400, 5, 50, 20, 80],
  ['torte', 'Torte (Sahne, Käse)', 'torte|sahnetorte|kaesekuchen|kaesetorte|kuchen sahne|cheesecake|tiramisu', 285, 5, 28, 17, 120],
  ['reiswaffel', 'Reiswaffeln / Maiswaffeln', 'reiswaffel|reiswaffeln|reiskuchen|maiswaffel|puffreis|dinkelwaffel', 374, 8, 80, 2.5, 8],
  ['cracker', 'Cracker', 'cracker|salzcracker|ritz|kekscracker|saltletts|brotchips|grissini', 450, 9, 63, 18, 4],
  ['proteinbrot', 'Proteinbrot / Low-Carb-Brot', 'proteinbrot|eiweissbrot|low carb brot|lowcarb brot|oopsie|eiweiss brot', 221, 25, 10, 9, 40],
  ['toast-vollkorn', 'Vollkorntoast (Scheibe)', 'toast vollkorn|dreikorntoast|vollkorn toast|buttertoast', 245, 9, 42, 3, 30],
  ['pizzateig', 'Pizzateig / Teig', 'pizzateig|hefeteig|blaetterteig roh|nudelteig|fladen|naan|pita|pitabrot', 270, 8, 52, 3, 80],
  // Getreide, Pasta & Co.
  ['nudeln-vollkorn', 'Vollkornnudeln (ungekocht)', 'vollkornnudeln|vollkornspaghetti|vollkornpasta|dinkelnudeln|vollkorn nudeln|linsennudeln|kichererbsennudeln', 334, 14, 64, 2.5],
  ['polenta', 'Polenta / Grieß', 'polenta|griess|maisgriess|weizengriess|hirse|buchweizen|amaranth|graupen|gerste|dinkel', 333, 8, 73, 1],
  ['popcorn', 'Popcorn', 'popcorn|popcorn salzig|popcorn suess|mikrowellen popcorn', 373, 12, 70, 5],
  ['seitan', 'Seitan', 'seitan|weizeneiweiss|veganes fleisch|sojageschnetzeltes|soja schnetzel', 138, 25, 5, 2],
  ['tempeh', 'Tempeh', 'tempeh', 200, 19, 9, 11],
  ['erbsenprotein', 'Erbsen-/Reisprotein (Pulver)', 'erbsenprotein|veganes proteinpulver|reisprotein|pflanzliches protein|vegan protein|casein|caseinpulver|mehrkomponenten protein', 390, 80, 5, 6, 30, undefined, 10],
  ['proteinshake-fertig', 'Proteinshake (fertig)', 'proteinshake fertig|protein drink|eiweissdrink|myprotein shake|fertig shake|protein milch|eiweissshake|shake fertig', 69, 10, 5, 1, undefined, 1.03],
  ['mehrkorn-flocken', 'Dinkel-/Roggenflocken', 'dinkelflocken|roggenflocken|haferkleie|weizenkleie|kleie|leinsamen geschrotet|flohsamen', 330, 12, 55, 5],
  ['knuspermuesli-schoko', 'Schoko-Müsli', 'schokomuesli|schoko muesli|crunchy muesli|knuspermuesli schoko|knusper muesli|kelloggs|nesquik cerealien', 440, 8, 66, 15, undefined, undefined, 10],
  ['cerealien-gezuckert', 'Cerealien (gezuckert)', 'gezuckerte cerealien|choco pops|froot loops|cini minis|honey pops|zuckerflocken', 385, 6, 84, 2.5],
  // Aufstriche & Saucen
  ['tahin', 'Tahin / Sesammus', 'tahin|tahini|sesammus|sesampaste', 576, 17, 1, 56, undefined, undefined, 16],
  ['margarine', 'Margarine', 'margarine|halbfettmargarine|streichfett|rama|becel|pflanzenmargarine|butterschmalz|schmalz', 723, 0.2, 0.5, 80, undefined, 0.95, 14],
  ['senf', 'Senf', 'senf|mittelscharfer senf|dijon|honigsenf|bbq sauce|barbecue sauce|grillsosse|currysosse|curry ketchup', 80, 5, 6, 4, undefined, undefined, 15],
  ['sahnesosse', 'Sahnesoße / Béchamel', 'sahnesosse|rahmsosse|bechamel|kaesesosse|champignonrahmsosse|hollandaise|sauce hollandaise|bratensosse|bratensoße|jägersoße|jaegersosse|pilzsosse', 124, 2.5, 6, 10, undefined, 1, 20],
  ['tzatziki', 'Tzatziki / Kräuterdip', 'tzatziki|joghurt dip|kraeuterdip|aioli|knoblauchsosse|raita|sourcreme dip', 111, 3.5, 4, 9, undefined, 1, 20],
  ['dressing', 'Salatdressing', 'dressing|salatsosse|vinaigrette|joghurtdressing|caesar dressing|italian dressing|french dressing|salat sauce', 306, 1, 8, 30, undefined, 1, 15],
  ['sojasauce-suess', 'Süße Saucen (Sweet Chili, Teriyaki)', 'sweet chili|sweet chilisauce|teriyaki|teriyakisauce|hoisin|austernsauce|fischsauce|asia sauce|sriracha', 150, 1.5, 35, 0.3, undefined, 1.1, 15],
  ['nussmus-mix', 'Nuss-Nougat-Aufstrich (ohne Zucker)', 'protein aufstrich|proteincreme|fitness nutella|zuckerfreie nutella|nuss nougat protein', 450, 18, 18, 33, undefined, undefined, 15],
  ['frischkaese-kraeuter', 'Frischkäse (Kräuter, Light)', 'frischkaese light|frischkaese kraeuter|frischkaese leicht|philadelphia light|frischkaese 0,2|doppelrahmfrischkaese', 140, 9, 4, 9, undefined, undefined, 20],
  // Süßes & Snacks
  ['schokoriegel', 'Schokoriegel', 'schokoriegel|snickers|twix|kitkat|kit kat|bounty|milky way|duplo|hanuta|knoppers|raffaello|kinder riegel|kinderriegel|kinder bueno|bueno', 470, 6, 62, 22, 50],
  ['muesliriegel', 'Müsliriegel', 'muesliriegel|haferriegel|getreideriegel|cerealienriegel|fruchtriegel|energieriegel|nussriegel|corny|clif|powerbar', 401, 6, 65, 13, 25],
  ['bonbons', 'Bonbons / Lakritz', 'bonbons|bonbon|lutscher|lakritz|lakritze|karamell|kaugummi|zuckerl|dragees|fruchtbonbons|haribo goldbaeren', 390, 0.5, 96, 0.3, 5],
  ['pralinen', 'Pralinen / Konfekt', 'praline|pralinen|konfekt|trüffel|trueffel|ferrero rocher|lindor|schokoladenkugeln|schokokugeln', 519, 5, 55, 31, 12],
  ['erdnussflips', 'Erdnussflips / Käsesnacks', 'erdnussflips|flips|cheetos|salzgebaeck|knabbergebaeck|erdnuss flips|brezelsticks|nachos', 502, 10, 57, 26],
  ['studentenfutter', 'Studentenfutter / Nussmix', 'studentenfutter|trail mix|nuss rosinen mix|nuss frucht mix|nuss und frucht|cashew mix|gesalzene nuesse', 478, 12, 40, 30],
  ['pistazien', 'Pistazien', 'pistazien|pistazie|macadamia|paranuss|paranuesse|pekannuss|pekannuesse|maronen|esskastanien', 598, 20, 17, 50, 1],
  ['zartbitterschokolade', 'Zartbitterschokolade', 'zartbitterschokolade|bitterschokolade|dunkle schokolade|zartbitter|schokolade 70|schokolade 85|edelbitter', 526, 6, 40, 38, 5],
  ['wassereis', 'Wassereis / Sorbet', 'wassereis|eis am stiel|sorbet|eis stiel|calippo|solero|eislutscher|slush|granita', 100, 0.5, 24, 0.1, 60],
  ['softeis', 'Eisbecher / Softeis', 'softeis|eisbecher|eiscreme|magnum|cornetto|ben und jerrys|eis becher|milchspeiseeis|eis waffel', 220, 3.5, 27, 11, 90],
  ['fruchtgummi-zuckerfrei', 'Proteinchips / Proteinsnack', 'proteinchips|protein chips|proteinsnack|protein snack|protein cookie|protein keks|proteinkeks|protein riegel soft|protein bar crunchy', 400, 32, 35, 14, 45],
  ['kekse-schoko', 'Schokokekse / Oreo', 'schokokekse|oreo|choco keks|schokokeks|doppelkeks|cookies|cookie|haferkekse|butterkekse|leibniz|prinzenrolle|duplo keks', 480, 5.5, 68, 21, 10],
  // Getränke (pro 100 ml)
  ['schorle', 'Saftschorle', 'apfelschorle|saftschorle|schorle|fruchtschorle|orangenschorle|rhabarberschorle', 22, 0.1, 5.2, 0, undefined, 1],
  ['bier', 'Bier', 'bier|pils|weizenbier|hefeweizen|kölsch|koelsch|radler|alsterwasser|malzbier|alkoholfreies bier|weizen', 43, 0.5, 3.5, 0, undefined, 1.01],
  ['wein', 'Wein / Sekt', 'wein|rotwein|weisswein|rosewein|sekt|prosecco|champagner|glühwein|gluehwein|aperol|aperol spritz|weinschorle|schaumwein', 75, 0.1, 2.5, 0, undefined, 0.99],
  ['spirituose', 'Schnaps / Spirituosen (40 %)', 'schnaps|wodka|whisky|whiskey|likoer|likör|jaegermeister|tequila|cognac|brandy|vodka|cocktail|longdrink|eierlikoer', 230, 0, 0, 0, undefined, 0.95],
  ['kaffee', 'Kaffee / Tee (ohne Zucker)', 'kaffee|tee|espresso|schwarzer kaffee|gruener tee|kraeutertee|fencheltee|pfefferminztee|filterkaffee|americano|schwarztee|matcha|ingwertee', 1, 0.1, 0, 0, undefined, 1],
  ['cappuccino', 'Cappuccino / Latte', 'cappuccino|latte macchiato|milchkaffee|kaffee mit milch|latte|flat white|cortado|kaffeespezialitaet|oatly latte|kaffee latte', 40, 2.5, 3.5, 1.8, undefined, 1],
  ['energydrink', 'Energydrink', 'energy|energydrink|red bull|monster|energy drink|rockstar|isostar|sportgetraenk|powerade|gatorade|isotonisch', 45, 0, 11, 0, undefined, 1.03],
  ['cola-zero', 'Cola Zero / Light-Getränke', 'cola zero|cola light|light getraenk|coke zero|pepsi max|fanta zero|sprite zero|light limo|zuckerfrei getraenk', 1, 0, 0, 0, undefined, 1],
  ['wasser', 'Wasser', 'wasser|mineralwasser|sprudel|leitungswasser|tafelwasser|stilles wasser|medium wasser', 0, 0, 0, 0, undefined, 1],
  ['kokoswasser', 'Kokoswasser / Gemüsesaft', 'kokoswasser|gemuesesaft|tomatensaft|karottensaft|rote bete saft|smoothie gemuese', 20, 0.5, 4, 0.1, undefined, 1.03],
  ['kakao-heiss', 'Heiße Schokolade', 'heisse schokolade|kakao|kakaogetraenk|trinkkakao|chai latte|chai|latte kakao|schokodrink', 80, 3.3, 11, 2.5, undefined, 1.03],
  // Fertiggerichte & Fast Food
  ['pizza-salami', 'Pizza Salami / Schinken', 'pizza salami|salamipizza|pizza schinken|pizza hawaii|pizza funghi|pizza tonno|pizza speciale|pizza diavola|pizza peperoni|pizza prosciutto|pizza vier kaese|pizza quattro formaggi', 264, 11, 28, 12, 350],
  ['lasagne', 'Lasagne / Cannelloni', 'lasagne|lasagna|cannelloni|auflauf|nudelauflauf|kartoffelauflauf|moussaka|gratin', 147, 8, 13, 7, 400],
  ['bolognese', 'Spaghetti Bolognese', 'bolognese|spaghetti bolognese|nudeln bolognese|spaghetti bolo|pasta bolognese|hackfleischsosse|ragu|ragù', 133, 6, 16, 5, 400],
  ['carbonara', 'Pasta Carbonara', 'carbonara|spaghetti carbonara|pasta carbonara|nudeln sahnesosse|pasta alfredo|alfredo|nudeln mit sahne|schinkennudeln', 188, 8, 22, 7.5, 400],
  ['chili-con-carne', 'Chili con Carne', 'chili con carne|chili|chilli|chilli con carne|bohneneintopf hack|texmex pfanne', 108, 8, 10, 4, 350],
  ['gulasch', 'Gulasch / Ragout', 'gulasch|rindergulasch|schweinegulasch|geschnetzeltes|ragout|rouladen|schmorbraten|sauerbraten|hackbraten|schweinshaxe|haxe', 127, 12, 4, 7, 300],
  ['eintopf', 'Eintopf / Suppe', 'eintopf|linsensuppe|erbsensuppe|gemuesesuppe|suppe|huehnersuppe|nudelsuppe|bohnensuppe|kartoffelsuppe|kuerbissuppe|tomatensuppe|brokkolisuppe|minestrone|gulaschsuppe', 58, 3, 8, 1.5, 350],
  ['fruehlingsrolle', 'Frühlingsrolle', 'fruehlingsrolle|fruehlingsrollen|springroll|samosa|teigtasche|gyoza|maultasche|maultaschen|ravioli|tortellini|dim sum|empanada', 210, 5, 25, 10, 80],
  ['ramen', 'Instantnudeln / Ramen', 'ramen|instantnudeln|asia nudeln|mie nudeln|asianudeln|cup noodles|nudelbecher|wok nudeln trocken', 447, 9, 60, 19, 80],
  ['asia-pfanne', 'Gebratene Nudeln / Reis (Asia)', 'gebratene nudeln|chow mein|nasi goreng|gebratener reis|bami goreng|pad thai|curry reis|asia pfanne|wok gericht|reispfanne|asia gericht', 158, 5, 22, 5.5, 400],
  ['falafel', 'Falafel', 'falafel|kichererbsenbaellchen|gemuesebaellchen|veggie baellchen|gemuesebratling|veggie burger|veggie patty|bratling', 342, 13, 32, 18, 17],
  ['spaetzle', 'Spätzle / Käsespätzle', 'kaesespaetzle|spaetzle|spätzle|kässpätzle|schupfnudeln|nockerl|haluschki', 183, 8, 22, 7, 300],
  ['flammkuchen', 'Flammkuchen / Quiche', 'flammkuchen|quiche|zwiebelkuchen|pizzabrot|fladenbrot belegt|sandwich|belegtes brot|panini|toast hawaii', 234, 8, 28, 10, 250],
  ['currywurst-pommes', 'Pommes mit Mayo / Ketchup', 'pommes mayo|pommes ketchup|pommes rot weiss|portion pommes|pommes schranke|pommes mit', 330, 4, 38, 18, 200],
  ['baguette-belegt', 'Belegtes Brötchen / Sandwich', 'belegtes broetchen|sandwich belegt|subway|baguette belegt|wrap belegt|dönerbrötchen', 230, 11, 28, 8, 220],
  ['reis-bowl', 'Reisgericht / Bowl (Fertiggericht)', 'poke bowl|reisbowl|buddha bowl|fertiggericht|mikrowellengericht|tiefkuehlgericht|tk gericht|fertigessen|mikrowelle', 130, 6, 17, 4, 400],
  ['hotdog', 'Hot Dog / Bratwurst im Brötchen', 'hotdog|hot dog|bratwurst broetchen|bratwurstbroetchen|wiener broetchen|curry brot|kebab teller|wuerstchen im schlafrock|schlafrock', 270, 10, 24, 15, 150],
  // weitere Beilagen, Getränke und Gerichte
  ['reisnudeln', 'Reisnudeln / Glasnudeln (ungekocht)', 'reisnudeln|glasnudeln|udon|soba|somen|sobanudeln|udonnudeln', 353, 7, 80, 0.6],
  ['fertigsalat', 'Salat mit Dressing (Fertig-/Restaurantsalat)', 'thunfischsalat|fertigsalat|salat mit dressing|caesar salad|griechischer salat|bauernsalat|tomatensalat|gurkensalat|chefsalat|bunter salat|salatteller', 116, 6, 5, 8, 250],
  ['edamame', 'Edamame / Sojabohnen', 'edamame|sojabohnen|sojabohne|lupinen|lupine', 113, 12, 5, 5],
  ['kraeuter', 'Kräuter / Frühlingszwiebel', 'fruehlingszwiebel|lauchzwiebel|schnittlauch|petersilie|kraeuter|basilikum|dill|koriander|minze', 30, 2, 4, 0.3, 5],
  ['linsen-gekocht', 'Linsen (gekocht / Dose)', 'gekochte linsen|linsen gekocht|linsen dose|linsen aus der dose|tellerlinsen', 108, 9, 17, 0.5],
  ['quinoa-gekocht', 'Quinoa (gekocht)', 'gekochte quinoa|quinoa gekocht', 119, 4.4, 21, 1.9],
  ['couscous-gekocht', 'Couscous (gekocht)', 'gekochter couscous|couscous gekocht|bulgur gekocht', 109, 3.8, 23, 0.2],
  ['haferbrei', 'Haferbrei (fertig mit Milch)', 'haferbrei fertig|porridge fertig|porridge mit milch|overnight oats|haferbrei mit milch', 99, 4, 14, 3, 300],
  ['ofenpommes', 'Ofenpommes / Kartoffelspalten', 'ofenpommes|backofenpommes|kartoffelspalten|wedges|country potatoes|kartoffel wedges', 162, 3, 24, 6],
  ['trinkjoghurt', 'Trinkjoghurt / Lassi', 'trinkjoghurt|lassi|ayran|joghurtdrink|joghurt drink|actimel|yakult|molkedrink', 65, 3, 10, 1.5, undefined, 1.03],
  ['milchshake', 'Milchshake / Frappé', 'milchshake|shake|frappe|bubble tea|eiskaffee|eiscafe', 111, 3, 17, 3.5, undefined, 1.03],
  ['lebkuchen', 'Lebkuchen / Weihnachtsgebäck', 'lebkuchen|spekulatius|dominosteine|printen|zimtsterne|vanillekipferl|weihnachtsgebaeck|stollenkonfekt|baklava|baumkuchen', 399, 5, 70, 11, 30],
  ['dosenobst', 'Dosenobst (gezuckert)', 'obst aus der dose|dosenobst|pfirsiche dose|ananas dose|fruchtcocktail|mandarinen dose|kompott|obstkonserve', 70, 0.4, 17, 0.1],
  ['rahmspinat', 'Rahmspinat', 'rahmspinat|sahnespinat|blattspinat tk', 60, 3, 3, 4],
  ['maiskolben', 'Maiskolben', 'maiskolben|mais gekocht|zuckermais kolben', 101, 3, 19, 1.5, 200],
  ['gruetze', 'Rote Grütze / Götterspeise', 'rote gruetze|goetterspeise|gelee dessert|wackelpudding|fruchtgruetze|gruetze', 85, 0.5, 20, 0.1],
  ['schweinebauch', 'Schweinebauch / Spareribs', 'schweinebauch|spareribs|rippchen|ripperl|krustenbraten|bauchfleisch|pulled pork|burnt ends', 303, 15, 0, 27],
  ['haehnchenfluegel', 'Hähnchenflügel', 'haehnchenfluegel|chicken wings|wings|fluegel|buffalo wings', 207, 18, 0, 15, 60],
  ['aufstrich-vegan', 'Brotaufstrich (vegan / Gemüse)', 'veganer aufstrich|brotaufstrich|aufstrich|bruschetta aufstrich|streichcreme|bruschetta|vegane streichcreme', 230, 5, 12, 18, undefined, undefined, 20],
];
